recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LdB7MMSAAAAAFAWKqlfREZ4Z88ZJZY0mEuVX7_6"
	privateKey = "6LdB7MMSAAAAABqAMkWSt0851tnHQ-ERInYxIDxI"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}